server:
  port: 8080
  servlet:
    session:
      timeout: 300s
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.89.51.123:3306/imooc-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: ljr
    password: ljr
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: redis
  redis:
    # database: 0
    host: 127.0.0.1
    password: root
    port: 6379
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
#      shutdown-timeout: 100ms
imooc:
  security:
    browser:
    # 登录页面
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
      loginType: JSON
      # 注册页面
      signUpUrl: /demo-signUp.html
    code:
      image:
        width: 100
        height: 50
        url: /order
    social:
      qq:
        app-id: 101316278
        app-secret: 34211e019a56566f7d44f4fe58380e69
    oauth2:
      clients:
        -
          clientId: myid
          clientSecret: myid
          redirectUris:
            - "http://example.com"
            - "http://ora.com"
          accessTokenValiditySeconds: 0
        -
          clientId: myid2
          clientSecret: myid2
          authorizedGrantTypes: ["refresh_token", "password"]
          redirectUris:
            - "http://example.com"
            - "localhost:8080"
          scopes: ["all", "read", "write"]
          accessTokenValiditySeconds: 7200

logging:
  level:
    root: info
    sun.rmi.transport.tcp: info
    sun.rmi.loader: info
    io.lettuce.core.protocol.CommandHandler: info
  path: log
# 自定义认证服务器配置后下面的配置就没有用了
security:
  oauth2:
    client:
      client-id: myid
      client-secret: myid
      registered-redirect-uri:
        - "http://example.com"
        - "http://ora.com"

